<?php
/**
 * Plugin Name: YNS GitHub Deploy Agent
 * Description: GitHub manifest -> SHA-256 -> Plugin Bridge -> staging -> verifica -> rollback per YOGANOSTRESS ADESSO.
 * Version: 1.0.0
 * Author: Yoganostress
 * Requires at least: 6.9
 * Requires PHP: 8.1
 */
if (!defined('ABSPATH')) exit;
final class YNS_GitHub_Deploy_Agent {
 private const STATE='yns_gda_state', LOCK='yns_gda_lock';
 private const MANIFEST='https://raw.githubusercontent.com/VitoPerillo/VitoPerillo.github.io/main/.yns-deploy/yoganostress-adesso/manifest.json';
 private const RAW_PREFIX='https://raw.githubusercontent.com/VitoPerillo/VitoPerillo.github.io/main/.yns-deploy/yoganostress-adesso/releases/';
 private const CHANNEL='yoganostress-adesso', SLUG='yoganostress-adesso', PLUGIN_FILE='yoganostress-adesso/yoganostress-adesso.php';
 public static function init():void{add_filter('cron_schedules',[self::class,'schedules']);add_action('yns_gda_check',[self::class,'check']);add_action('init',[self::class,'ensure']);add_action('rest_api_init',[self::class,'rest']);}
 public static function activate():void{self::ensure();self::set(['status'=>'idle','message'=>'Agent attivo.']);}
 public static function deactivate():void{$t=wp_next_scheduled('yns_gda_check');if($t)wp_unschedule_event($t,'yns_gda_check');}
 public static function schedules(array $s):array{$s['yns_gda_minute']=['interval'=>60,'display'=>'YNS Deploy Agent ogni minuto'];return $s;}
 public static function ensure():void{if(!wp_next_scheduled('yns_gda_check'))wp_schedule_event(time()+20,'yns_gda_minute','yns_gda_check');}
 public static function rest():void{register_rest_route('yns-github-deploy/v1','/status',['methods'=>'GET','callback'=>[self::class,'status'],'permission_callback'=>'__return_true']);}
 public static function status():WP_REST_Response{self::ensure();$s=self::state();return new WP_REST_Response(['agent_version'=>'1.0.0','channel'=>self::CHANNEL,'plugin_slug'=>self::SLUG,'deployment_id'=>(string)($s['deployment_id']??''),'version'=>(string)($s['version']??''),'status'=>(string)($s['status']??'idle'),'message'=>(string)($s['message']??''),'updated_at'=>(string)($s['updated_at']??'')],200);}
 private static function state():array{$v=get_option(self::STATE,[]);return is_array($v)?$v:[];}
 private static function set(array $p):void{update_option(self::STATE,array_merge(self::state(),$p,['updated_at'=>gmdate('c')]),false);}
 private static function lock():bool{$v=get_option(self::LOCK,[]);if(is_array($v)&&!empty($v['ts'])&&(time()-(int)$v['ts'])<300)return false;update_option(self::LOCK,['ts'=>time()],false);return true;}
 private static function unlock():void{delete_option(self::LOCK);}
 private static function fail(string $id,string $ver,string $msg,string $status='failed'):void{self::set(['deployment_id'=>$id,'version'=>$ver,'status'=>$status,'message'=>mb_substr($msg,0,500)]);}
 private static function json(string $url):array{$r=wp_remote_get($url,['timeout'=>20,'redirection'=>2,'headers'=>['Cache-Control'=>'no-cache']]);if(is_wp_error($r))throw new RuntimeException($r->get_error_message());if((int)wp_remote_retrieve_response_code($r)!==200)throw new RuntimeException('Manifest HTTP non valido.');$j=json_decode((string)wp_remote_retrieve_body($r),true);if(!is_array($j))throw new RuntimeException('Manifest JSON non valido.');return $j;}
 private static function manifest(array $m):array{foreach(['schema','channel','action','deployment_id','plugin_slug','version','package_url','package_sha256','issued_at','expires_at'] as $k)if(!array_key_exists($k,$m))throw new RuntimeException('Manifest incompleto: '.$k);if((int)$m['schema']!==1||$m['channel']!==self::CHANNEL||$m['plugin_slug']!==self::SLUG)throw new RuntimeException('Manifest fuori canale.');if(!in_array($m['action'],['none','deploy'],true))throw new RuntimeException('Azione manifest non valida.');if($m['action']==='none')return $m;$id=preg_replace('/[^a-zA-Z0-9._-]/','',(string)$m['deployment_id']);if($id===''||$id!==(string)$m['deployment_id'])throw new RuntimeException('deployment_id non valido.');if(!preg_match('/^\d+\.\d+\.\d+(?:[-+][A-Za-z0-9._-]+)?$/',(string)$m['version']))throw new RuntimeException('Versione non valida.');if(!preg_match('/^[a-f0-9]{64}$/',(string)$m['package_sha256']))throw new RuntimeException('SHA-256 non valido.');if(!str_starts_with((string)$m['package_url'],self::RAW_PREFIX))throw new RuntimeException('Origine pacchetto non autorizzata.');$n=time();$i=strtotime((string)$m['issued_at']);$e=strtotime((string)$m['expires_at']);if(!$i||!$e||$i>$n+300||$e<$n||($e-$i)>21600)throw new RuntimeException('Finestra temporale manifest non valida.');return $m;}
 private static function version():string{require_once ABSPATH.'wp-admin/includes/plugin.php';$p=get_plugins('/'.self::SLUG);return isset($p['yoganostress-adesso.php'])?(string)($p['yoganostress-adesso.php']['Version']??''):'';}
 private static function verify(string $v):void{require_once ABSPATH.'wp-admin/includes/plugin.php';if(self::version()!==$v)throw new RuntimeException('Versione installata diversa.');if(!is_plugin_active(self::PLUGIN_FILE))throw new RuntimeException('Plugin non attivo.');$p=wp_remote_get(rest_url('ysad/v1/plans'),['timeout'=>20]);if(is_wp_error($p)||(int)wp_remote_retrieve_response_code($p)!==200)throw new RuntimeException('REST plans non 200.');$pj=json_decode((string)wp_remote_retrieve_body($p),true);if(!is_array($pj)||count($pj)<1)throw new RuntimeException('REST plans vuoto.');$t=wp_remote_post(rest_url('ysad/v1/test'),['timeout'=>25,'headers'=>['Content-Type'=>'application/json'],'body'=>wp_json_encode(['mind'=>2,'tension'=>1,'energy'=>2,'rest'=>2,'pain_state'=>'none','symptom_change'=>'stable','available_minutes'=>7])]);if(is_wp_error($t)||(int)wp_remote_retrieve_response_code($t)!==200)throw new RuntimeException('RESET TEST non 200.');$tj=json_decode((string)wp_remote_retrieve_body($t),true);if(!is_array($tj)||empty($tj['practice']['id']))throw new RuntimeException('RESET TEST senza pratica valida.');}
 public static function check():void{if(!self::lock())return;$tmp='';try{if(!class_exists('PHB_Deployer')||!class_exists('PHB_Validator')||!class_exists('PHB_Registry'))throw new RuntimeException('Plugin Bridge non disponibile.');if(!PHB_Registry::is_managed(self::SLUG))throw new RuntimeException('YOGANOSTRESS ADESSO non è nella allowlist Bridge.');$m=self::manifest(self::json(self::MANIFEST));if($m['action']==='none'){self::set(['status'=>'idle','message'=>'Nessun deploy pendente.']);return;}$id=(string)$m['deployment_id'];$v=(string)$m['version'];$s=self::state();if(($s['deployment_id']??'')===$id&&in_array(($s['status']??''),['verified','rolled_back','failed'],true))return;$cur=self::version();if($cur!==''&&version_compare($v,$cur,'<'))throw new RuntimeException('Downgrade automatico rifiutato.');self::set(['deployment_id'=>$id,'version'=>$v,'status'=>'downloading','message'=>'Scarico e verifico SHA-256.']);require_once ABSPATH.'wp-admin/includes/file.php';$tmp=download_url((string)$m['package_url'],60);if(is_wp_error($tmp))throw new RuntimeException($tmp->get_error_message());if(filesize($tmp)>20*1024*1024)throw new RuntimeException('Pacchetto oltre 20 MB.');if(!hash_equals((string)$m['package_sha256'],hash_file('sha256',$tmp)))throw new RuntimeException('SHA-256 pacchetto non corrispondente.');$meta=PHB_Validator::inspect_zip($tmp);if(($meta['slug']??'')!==self::SLUG||($meta['plugin_file']??'')!==self::PLUGIN_FILE||($meta['version']??'')!==$v)throw new RuntimeException('Metadata ZIP non coerenti.');self::set(['status'=>'deploying','message'=>'SHA-256 OK. Deploy atomico via Plugin Bridge.']);$r=PHB_Deployer::deploy($tmp,$meta,true);$b=(string)($r['backup_id']??'');try{self::verify($v);self::set(['status'=>'verified','message'=>'Deploy verificato: versione, attivazione, plans REST e RESET TEST OK.','backup_id'=>$b]);}catch(Throwable $x){if($b!==''){PHB_Deployer::rollback($b);self::fail($id,$v,'Verifica fallita; rollback eseguito: '.$x->getMessage(),'rolled_back');}else self::fail($id,$v,'Verifica fallita, backup non disponibile: '.$x->getMessage());}}catch(Throwable $e){$s=self::state();self::fail((string)($s['deployment_id']??''),(string)($s['version']??''),$e->getMessage());}finally{if(is_string($tmp)&&$tmp!==''&&file_exists($tmp))@unlink($tmp);self::unlock();}}
}
register_activation_hook(__FILE__,['YNS_GitHub_Deploy_Agent','activate']);
register_deactivation_hook(__FILE__,['YNS_GitHub_Deploy_Agent','deactivate']);
add_action('plugins_loaded',['YNS_GitHub_Deploy_Agent','init']);
